python cli.py train \
  --dataset mnist_train \
  --architecture architecture.json \
  --loss categorical_crossentropy \
  --optimizer adam \
  --lr 0.001 \
  --max-samples 5000 \
  --epochs 200 \
  --batch-size 32 \
  --eval-every 1 \
  --patience 100 \
  --val-split 0.2 \
  --metrics accuracy precision recall f1 \
  --scheduler cosineannealinglr \
  --scheduler-args '{"T_max": 500, "eta_min": 1e-6}' \
  --save models/'mnist model' \
  --live-plot
